### ISSUE TITLE
Not working on Node 12 because of graceful-fs 3

### ISSUE THREAD

**Issue by nevi-me** [zaucy/grpc-gen#4]
`graceful-fs:3` uses `natives` module, which doesn't work on Node 12 because of the below error. 
`graceful-fs:4` no longer depends on `natives`, and so should solve the problem (https://github.com/isaacs/node-graceful-fs).

```js
PS D:\myproject> grpc-gen --watch --verbose
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\me\AppData\Roaming\npm\node_modules\grpc-gen\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\me\AppData\Roaming\npm\node_modules\grpc-gen\node_modules\natives\index.js:55
:10)
    at Object.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\grpc-gen\node_modules\fstream\node_modules\
graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by nevi-me** [comment]
Looks like the dependency tree runs deeper than I thought. I'm checking what module needs to be upgraded, I'll submit a PR if I come right
